Fixed whitespace issues
Fixed the whitespace issues with sysDescr causing: 
SyntaxError: unterminated string literal
return overlib('<div style=\'background-color: #FFFFFF;\'><div><span class=

This was stopping minigraphs from loading.